### Lab2. Design of Logic Gates using Perceptron and Keras

#### 225229138 - Sowmiya B

### Part-I: Design OR gate using the concept of Perceptron

Step1: Define helper functions

In [1]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [2]:
def logic_gate(w1, w2, b):
# Helper to create logic gate functions
    return lambda x1, x2: sigmoid(w1 * x1 + w2 * x2 + b)

In [3]:
def test(gate):
# Helper function to test out our weight functions.
    for a, b in (0, 0), (0, 1), (1, 0), (1, 1):
        print("{}, {}: {}".format(a, b, np.round(gate(a,b))))

Step2: Identify values for weights, w1 and w2 and bias, b, for OR gate.
Then, call logic_gate() function first with the values of weights and bias and
test the outputs. For example, do the following steps and verify OR gate
operations.

In [4]:
or_gate = logic_gate(20, 20, -10)

In [5]:
test(or_gate)

0, 0: 0.0
0, 1: 1.0
1, 0: 1.0
1, 1: 1.0


### Part-II: Implement the operations of AND, NOR and NAND gates

Step1: Identify values for weights, w1 and w2 and bias, b, for AND gate.
Then, call logic_gate() function first with the values of weights and bias and
test the outputs. Draw manually using pen the diagram of OR gate.

In [6]:
and_gate=logic_gate(10,10,-10)

In [7]:
test(and_gate)

0, 0: 0.0
0, 1: 0.0
1, 0: 0.0
1, 1: 1.0


Step2: Identify values for weights, w1 and w2 and bias, b, for NOR gate.
Then, call logic_gate() function first with the values of weights and bias and
test the outputs. Draw manually using pen the diagram of NOR gate.

In [8]:
nor_gate = logic_gate(-20,-20,10)
test(nor_gate)

0, 0: 1.0
0, 1: 0.0
1, 0: 0.0
1, 1: 0.0


Step3:Identify values for weights, w1 and w2 and bias, b, for NAND gate. Then, call logic_gate() function first with the
values of weights and bias and test the outputs. Draw manually using pen the diagram of NAND gate.

In [9]:
nand_gate = logic_gate(-1,-1,2)
test(nand_gate)

0, 0: 1.0
0, 1: 1.0
1, 0: 1.0
1, 1: 0.0


### Part-III: Limitations of single neuron for XOR operation

Can you identify a set of weights such that a single neuron can output the values for XOR gate?. Single
neurons can't correlate inputs, so it's just confused. So individual neurons are out. Can we still use neurons to
somehow form an XOR gate?.

In [10]:
def xor_gate(a,b):
    c=or_gate(a,b)
    d=nand_gate(a,b)
    return and_gate(c,d)
test(xor_gate)

0, 0: 0.0
0, 1: 1.0
1, 0: 1.0
1, 1: 1.0


In [11]:
def logic_gate(w1, W2, b):
    return lambda x1, x2: sigmoid(w1 * x1 + W2 * x2 + b)
def final(gate):
    for a, b in zip(result1, result2):
        print("{}, {}: {}".format(a, b, np.round(gate(a, b))))
result1 = []
result2 = []
or_gate = logic_gate(20,20,-10)

for a, b in (0, 0), (0, 1), (1, 0), (1, 1):
    result1.append(np.round(or_gate(a,b)))
    nand_gate = logic_gate(-23,-25,35)
for a, b in (0, 0), (0, 1), (1, 0), (1, 1):
    result2.append(np.round(nand_gate(a,b)))
    
xor_gate = logic_gate(20,20,-30)

print("XOR Gate truth table \n")
print("X, Y X+Y")
final(xor_gate)

XOR Gate truth table 

X, Y X+Y
0.0, 1.0: 0.0
1.0, 1.0: 1.0
1.0, 1.0: 1.0
1.0, 0.0: 0.0


### Part-IV: Logic Gates using Keras library

In this part of the lab, you will create and implement the operations of logic gates such as AND, OR, NOT,
NAND, NOR and XOR in Keras.

Steps: For each logic gate operations
1. Create a tensor using Numpy array for input values and output
values
2. Create a neural network with one hidden layer with 16 nodes, input
dimensions to be 2 and “relu” activation function. The output layer
should have one node with sigmoid activation function.
3. Compile the model with “adam” optimizer, 'mean_squared_error' loss
function and 'binary_accuracy' as performance or metric.
4. Run the model with 100 epoch and predict the output values.

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
# Function to create and run the model
def run_logic_gate_model(gate_name, x_train, y_train):
    # Create the model
    model = Sequential()
    model.add(Dense(16, input_dim=2, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    # Compile the model
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['binary_accuracy'])

    # Train the model
    model.fit(x_train, y_train, epochs=100, verbose=0)

    # Predict the output values
    predictions = model.predict(x_train)
    predictions = np.round(predictions)

    # Print the predictions
    print(f"{gate_name} Gate Predictions:")
    print(predictions.flatten().astype(int))
    print()

In [14]:
# Input and output values for the logic gates
input_values = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# AND gate
and_output = np.array([0, 0, 0, 1])
run_logic_gate_model("AND", input_values, and_output)

# OR gate
or_output = np.array([0, 1, 1, 1])
run_logic_gate_model("OR", input_values, or_output)

# NOT gate
not_output = np.array([1, 0, 1, 0])
run_logic_gate_model("NOT", input_values, not_output)

# NAND gate
nand_output = np.array([1, 1, 1, 0])
run_logic_gate_model("NAND", input_values, nand_output)

# NOR gate
nor_output = np.array([1, 0, 0, 0])
run_logic_gate_model("NOR", input_values, nor_output)

# XOR gate
xor_output = np.array([0, 1, 1, 0])
run_logic_gate_model("XOR", input_values, xor_output)

1/1 [==============================] - 0s 78ms/step
AND Gate Predictions:
[0 0 0 1]

1/1 [==============================] - 0s 47ms/step
OR Gate Predictions:
[1 1 1 1]

1/1 [==============================] - 0s 59ms/step
NOT Gate Predictions:
[1 0 1 0]

1/1 [==============================] - 0s 47ms/step
NAND Gate Predictions:
[1 1 1 0]

1/1 [==============================] - 0s 47ms/step
NOR Gate Predictions:
[0 0 0 0]

1/1 [==============================] - 0s 70ms/step
XOR Gate Predictions:
[1 1 1 0]

